AWSTemplateFormatVersion: '2010-09-09'
Description: StepFunctions for TestDocker

Parameters:
  SystemName:
    Type: String
    AllowedPattern: '[a-zA-Z0-9-]*'
  EnvType:
    Description: Environment type.
    Type: String
    Default: dev
    AllowedValues: [all, dev, stg, prod]
    ConstraintDescription: must specify all, dev, stg, or prod.
  StateMachineType:
    Description: StateMachine type.
    Type: String
    Default: STANDARD
    AllowedValues: [STANDARD, EXPRESS]
    ConstraintDescription: must specify STANDARD or EXPRESS.
  isIncludeExecutionData:
    Description: StateMachine IncludeExecutionData.
    Type: String
    Default: false
    AllowedValues: [false, true]
    ConstraintDescription: must specify false or true.
  isAssignPublicIp:
    Type: String
    AllowedValues: [ENABLED, DISABLED]

Mappings:
  AzMap:
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1c
      3rd: ap-northeast-1d

Resources:
  # # StateMachine 作成
  # # TestDockerECSRunTask
  # # ECSRunTask (Simple)
  # StepFunctionsStateMachineTestDockerECSRunTask:
  #   Type: AWS::StepFunctions::StateMachine
  #   Properties:
  #     StateMachineName: !Sub
  #       - ${SystemName}-${EnvType}-state-machine-testdocker-ecsruntask
  #       - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
  #     DefinitionString: !Sub
  #       - |
  #         {
  #           "Comment": "ECSRunTask",
  #           "StartAt": "ECSRunTask",
  #           "States": {
  #             "ECSRunTask": {
  #               "Type": "Task",
  #               "Resource": "arn:aws:states:::ecs:runTask",
  #               "InputPath": "$",
  #               "Parameters": {
  #                 "LaunchType": "FARGATE",
  #                 "Cluster": "${ECS_CLUSTER_ARN}",
  #                 "TaskDefinition": "${ECS_TASK_DEF_ARN}",
  #                 "NetworkConfiguration": {
  #                   "AwsvpcConfiguration": {
  #                     "AssignPublicIp": "${IS_ASSIGN_PUBLIC_IP}",
  #                     "SecurityGroups": [
  #                       "${SECURITY_GROUPS}"
  #                     ],
  #                     "Subnets": [
  #                       "${SUBNETS}"
  #                     ]
  #                   }
  #                 }
  #               },
  #               "End": true,
  #               "Retry": [
  #                 {
  #                   "ErrorEquals": [
  #                     "States.ALL"
  #                   ],
  #                   "IntervalSeconds": 1,
  #                   "BackoffRate": 1,
  #                   "MaxAttempts": 5
  #                 }
  #               ]
  #             }
  #           }
  #         }
  #       - {
  #           REGION: !Ref AWS::Region,
  #           ACCOUNT_ID: !Ref AWS::AccountId,
  #           SYSTEM_NAME: !Ref SystemName,
  #           ENV_TYPE: !Ref EnvType,
  #           ECS_TASK_DEF_ARN:
  #             {'Fn::ImportValue': !Sub '${SystemName}-${EnvType}-ecs-def-testdocker-arn'}, # タスク定義設定
  #           ECS_CLUSTER_ARN:
  #             {'Fn::ImportValue': !Sub '${SystemName}-${EnvType}-ecs-cluster-testdocker-arn'}, # ECSクラスター設定
  #           IS_ASSIGN_PUBLIC_IP: !Ref isAssignPublicIp,
  #           SECURITY_GROUPS:
  #             {'Fn::ImportValue': !Sub '${SystemName}-${EnvType}-ecs-sg'},
  #           SUBNETS:
  #             {'Fn::ImportValue': !Sub '${SystemName}-${EnvType}-private-subnet1'}, # サブネット設定
  #         }
  #     RoleArn:
  #       Fn::ImportValue: !Sub
  #         - ${SystemName}-${EnvType}-role-step-functions-${AWS::Region}
  #         - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
  #     StateMachineType: !Ref StateMachineType
  #     LoggingConfiguration:
  #       IncludeExecutionData: !Ref isIncludeExecutionData
  #       Level: 'OFF'
  #     Tags:
  #       - Key: Name
  #         Value: !Sub
  #           - ${SystemName}-${EnvType}-state-machine-testdocker-ecsruntask
  #           - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
  #       - Key: SystemName
  #         Value: !Ref SystemName
  #       - Key: EnvType
  #         Value: !Ref EnvType

  # # TestDockerECSRunTask
  # # ECSRunTask (Error ReRun:5)
  # StepFunctionsStateMachineTestDockerECSRunTask:
  #   Type: AWS::StepFunctions::StateMachine
  #   Properties:
  #     StateMachineName: !Sub
  #       - ${SystemName}-${EnvType}-state-machine-testdocker-ecsruntask
  #       - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
  #     DefinitionString: !Sub
  #       - |
  #         {
  #           "Comment": "ECSRunTask",
  #           "StartAt": "ECSRunTask",
  #           "States": {
  #             "ECSRunTask": {
  #               "Type": "Task",
  #               "Resource": "arn:aws:states:::ecs:runTask.sync",
  #               "InputPath": "$",
  #               "Parameters": {
  #                 "LaunchType": "FARGATE",
  #                 "Cluster": "${ECS_CLUSTER_ARN}",
  #                 "TaskDefinition": "${ECS_TASK_DEF_ARN}",
  #                 "NetworkConfiguration": {
  #                   "AwsvpcConfiguration": {
  #                     "AssignPublicIp": "${IS_ASSIGN_PUBLIC_IP}",
  #                     "SecurityGroups": [
  #                       "${SECURITY_GROUPS}"
  #                     ],
  #                     "Subnets": [
  #                       "${SUBNETS}"
  #                     ]
  #                   }
  #                 }
  #               },
  #               "End": true,
  #               "Retry": [
  #                 {
  #                   "ErrorEquals": [
  #                     "States.ALL"
  #                   ],
  #                   "IntervalSeconds": 1,
  #                   "BackoffRate": 1,
  #                   "MaxAttempts": 5
  #                 }
  #               ]
  #             }
  #           }
  #         }
  #       - {
  #           REGION: !Ref AWS::Region,
  #           ACCOUNT_ID: !Ref AWS::AccountId,
  #           SYSTEM_NAME: !Ref SystemName,
  #           ENV_TYPE: !Ref EnvType,
  #           ECS_TASK_DEF_ARN:
  #             {'Fn::ImportValue': !Sub '${SystemName}-${EnvType}-ecs-def-testdocker-arn'}, # タスク定義設定
  #           ECS_CLUSTER_ARN:
  #             {'Fn::ImportValue': !Sub '${SystemName}-${EnvType}-ecs-cluster-testdocker-arn'}, # ECSクラスター設定
  #           IS_ASSIGN_PUBLIC_IP: !Ref isAssignPublicIp,
  #           SECURITY_GROUPS:
  #             {'Fn::ImportValue': !Sub '${SystemName}-${EnvType}-ecs-sg'},
  #           SUBNETS:
  #             {'Fn::ImportValue': !Sub '${SystemName}-${EnvType}-private-subnet1'}, # サブネット設定
  #         }
  #     RoleArn:
  #       Fn::ImportValue: !Sub
  #         - ${SystemName}-${EnvType}-role-step-functions-${AWS::Region}
  #         - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
  #     StateMachineType: !Ref StateMachineType
  #     LoggingConfiguration:
  #       IncludeExecutionData: !Ref isIncludeExecutionData
  #       Level: 'OFF'
  #     Tags:
  #       - Key: Name
  #         Value: !Sub
  #           - ${SystemName}-${EnvType}-state-machine-testdocker-ecsruntask
  #           - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
  #       - Key: SystemName
  #         Value: !Ref SystemName
  #       - Key: EnvType
  #         Value: !Ref EnvType

  # TestDockerECSRunTask
  # ECSRunTask (Error ReRun:5 Error SNS:Publish)
  StepFunctionsStateMachineTestDockerECSRunTask:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub
        - ${SystemName}-${EnvType}-state-machine-testdocker-ecsruntask
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      DefinitionString: !Sub
        - |
          {
            "Comment": "ECSRunTask",
            "StartAt": "ECSRunTask",
            "States": {
              "ECSRunTask": {
                "Type": "Task",
                "Resource": "arn:aws:states:::ecs:runTask.sync",
                "InputPath": "$",
                "Parameters": {
                  "LaunchType": "FARGATE",
                  "Cluster": "${ECS_CLUSTER_ARN}",
                  "TaskDefinition": "${ECS_TASK_DEF_ARN}",
                  "NetworkConfiguration": {
                    "AwsvpcConfiguration": {
                      "AssignPublicIp": "${IS_ASSIGN_PUBLIC_IP}",
                      "SecurityGroups": [
                        "${SECURITY_GROUPS}"
                      ],
                      "Subnets": [
                        "${SUBNETS}"
                      ]
                    }
                  }
                },
                "Retry": [
                  {
                    "ErrorEquals": [
                      "States.ALL"
                    ],
                    "IntervalSeconds": 1,
                    "BackoffRate": 1,
                    "MaxAttempts": 5
                  }
                ],
                "Catch": [
                  {
                    "ErrorEquals": [
                      "States.ALL"
                    ],
                    "Next": "SNS Publish"
                  }
                ],
                "End": true
              },
              "SNS Publish": {
                "Type": "Task",
                "Resource": "arn:aws:states:::sns:publish",
                "Parameters": {
                  "Message.$": "$",
                  "TopicArn": "${TOPIC_ARN}"
                },
                "End": true
              }
            }
          }
        - {
            REGION: !Ref AWS::Region,
            ACCOUNT_ID: !Ref AWS::AccountId,
            SYSTEM_NAME: !Ref SystemName,
            ENV_TYPE: !Ref EnvType,
            ECS_TASK_DEF_ARN:
              {'Fn::ImportValue': !Sub '${SystemName}-${EnvType}-ecs-def-testdocker-arn'}, # タスク定義設定
            ECS_CLUSTER_ARN:
              {'Fn::ImportValue': !Sub '${SystemName}-${EnvType}-ecs-cluster-testdocker-arn'}, # ECSクラスター設定
            IS_ASSIGN_PUBLIC_IP: !Ref isAssignPublicIp,
            SECURITY_GROUPS:
              {'Fn::ImportValue': !Sub '${SystemName}-${EnvType}-ecs-sg'},
            SUBNETS:
              {'Fn::ImportValue': !Sub '${SystemName}-${EnvType}-private-subnet1'}, # サブネット設定
            TOPIC_ARN:
              {'Fn::ImportValue': !Sub '${SystemName}-${EnvType}-sns-topic-step-functions-arn'}, # SNSトピック設定
          }
      RoleArn:
        Fn::ImportValue: !Sub
          - ${SystemName}-${EnvType}-role-step-functions-${AWS::Region}
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      StateMachineType: !Ref StateMachineType
      LoggingConfiguration:
        IncludeExecutionData: !Ref isIncludeExecutionData
        Level: 'OFF'
      Tags:
        - Key: Name
          Value: !Sub
            - ${SystemName}-${EnvType}-state-machine-testdocker-ecsruntask
            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

Outputs:
  StepFunctionsStateMachineTestDockerECSRunTaskName:
    Value: !GetAtt StepFunctionsStateMachineTestDockerECSRunTask.Name
    Export:
      Name: !Sub
        - ${SystemName}-${EnvType}-state-machine-testdocker-ecsruntask-name
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
  StepFunctionsStateMachineTestDockerECSRunTaskArn:
    Value: !Ref StepFunctionsStateMachineTestDockerECSRunTask
    Export:
      Name: !Sub
        - ${SystemName}-${EnvType}-state-machine-testdocker-ecsruntask-arn
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}